[package]
name = "openapi-check"
edition = "2024"
version.workspace = true
publish = false

[dependencies]
tokio = { version = "1.43.0", features = ["fs", "macros", "rt", "rt-multi-thread"] }
hack4krak-backend = { path = "../" }
