services:
  db:
    container_name: hack4krak_postgres
    image: postgres:latest
    restart: on-failure
    shm_size: 128mb
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hack4krak
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    profiles:
      - db
      - all

  backend:
    container_name: hack4krak_backend
    build:
        context: .
        dockerfile: backend/Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    profiles:
      - backend
      - all
    env_file:
      - .env

  frontend:
    container_name: hack4krak_frontend
    build:
        context: .
        dockerfile: frontend/Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
    profiles:
      - frontend
      - all

volumes:
  database: