app = 'hack4krak-backend'
primary_region = 'fra'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.name_of_your_http_check]
    grace_period = "60s"
    interval = "30s"
    method = "get"
    path = "/"
    port = 8080
    timeout = "10s"
    type = "http"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
