export const organizers = {
  team: [
    {
      name: 'Adam Nowak',
      email: 'testmail@hack4krak.pl',
      role: 'jakas fajna rola',
      github: 'https://github.com/Hack4Krak/Hack4KrakSite',
      linkedin: 'https://pl.linkedin.com/company/hack4krak',
      section: 'zarząd',
    },
    {
      name: 'Adam Nowak',
      email: 'testmail@hack4krak.pl',
      role: 'jakas fajna rola',
      github: 'https://github.com/Hack4Krak/Hack4KrakSite',
      linkedin: 'https://pl.linkedin.com/company/hack4krak',
      section: 'zarząd',
    },
    {
      name: 'Adam Nowak',
      email: 'testmail@hack4krak.pl',
      role: 'jakas fajna rola',
      github: 'https://github.com/Hack4Krak/Hack4KrakSite',
      linkedin: 'https://pl.linkedin.com/company/hack4krak',
      section: 'zarząd',
    },
    {
      name: 'Adam Nowak',
      email: 'testmail@hack4krak.pl',
      role: 'jakas fajna rola',
      github: 'https://github.com/Hack4Krak/Hack4KrakSite',
      linkedin: 'https://pl.linkedin.com/company/hack4krak',
      section: 'zarząd',
    },
    {
      name: 'Adam Nowak',
      email: 'testmail@hack4krak.pl',
      role: 'jakas fajna rola',
      github: 'https://github.com/Hack4Krak/Hack4KrakSite',
      linkedin: 'https://pl.linkedin.com/company/hack4krak',
      section: 'sekcja techniczna',
    },
    {
      name: 'Adam Nowak',
      email: 'testmail@hack4krak.pl',
      role: 'jakas fajna rola',
      github: 'https://github.com/Hack4Krak/Hack4KrakSite',
      linkedin: 'https://pl.linkedin.com/company/hack4krak',
      section: 'sekcja techniczna',
    },
    {
      name: 'Adam Nowak',
      email: 'testmail@hack4krak.pl',
      role: 'jakas fajna rola',
      github: 'https://github.com/Hack4Krak/Hack4KrakSite',
      linkedin: 'https://pl.linkedin.com/company/hack4krak',
      section: 'sekcja techniczna',
    },
    {
      name: 'Adam Nowak',
      email: 'testmail@hack4krak.pl',
      role: 'jakas fajna rola',
      github: 'https://github.com/Hack4Krak/Hack4KrakSite',
      linkedin: 'https://pl.linkedin.com/company/hack4krak',
      section: 'sekcja techniczna',
    },
    {
      name: 'Adam Nowak',
      email: 'testmail@hack4krak.pl',
      role: 'jakas fajna rola',
      github: 'https://github.com/Hack4Krak/Hack4KrakSite',
      linkedin: 'https://pl.linkedin.com/company/hack4krak',
      section: 'graficy',
    },
    {
      name: 'Adam Nowak',
      email: 'testmail@hack4krak.pl',
      role: 'jakas fajna rola',
      github: 'https://github.com/Hack4Krak/Hack4KrakSite',
      linkedin: 'https://pl.linkedin.com/company/hack4krak',
      section: 'graficy',
    },
  ],
  hierarchy: ['zarząd', 'sekcja techniczna', 'graficy'],
}
