EmailConfirmation:
  subject: Potwierdzenie rejestracji
  sender_name: Autoryzacja Hack4Krak

ExternalRegistrationForm:
  subject: Rejestracja szkoły w CTF
  sender_name: Kontakt Hack4Krak

ResetPassword:
  subject: Zresetuj hasło
  sender_name: Autoryzacja Hack4Krak

Informational:
  subject: Informacje o Hack4Krak
  sender_name: Kontakt Hack4Krak