[package]
name = "migration"
version.workspace = true
edition.workspace = true

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
tokio.workspace = true

[dependencies.sea-orm-migration]
version = "1.1.11"
features = ["runtime-tokio-rustls", "sqlx-postgres" ]
