//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_roles")]
pub enum UserRoles {
    #[sea_orm(string_value = "admin")]
    Admin,
    #[sea_orm(string_value = "default")]
    Default,
    #[sea_orm(string_value = "owner")]
    Owner,
}
