//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use super::sea_orm_active_enums::CtfExperience;
use super::sea_orm_active_enums::SchoolGrade;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    hack4krak_macros :: DeriveUpdatableModel,
    utoipa :: ToSchema,
    Default,
)]
#[sea_orm(table_name = "user_onboarding")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub location: String,
    pub organization: String,
    pub marketing_consent: bool,
    pub marketing_consent_accepted_at: DateTime,
    pub marketing_consent_updated_at: DateTime,
    pub referral_sources: Option<Json>,
    pub ctf_experience: CtfExperience,
    pub school_grade: SchoolGrade,
    pub collab_interest: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::users::Entity")]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
