name: CD
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-arg GIT_ACCESS_TOKEN=${{ secrets.GIT_ACCESS_TOKEN }} --build-arg GIT_REPO=${{ secrets.GIT_REPO }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
