//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    pub username: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub email: String,
    pub created_at: DateTime,
    pub team_name: Option<String>,
    pub permissions: Option<Vec<String>>,
    #[sea_orm(unique)]
    pub leads: Option<String>,
    pub password: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::teams::Entity",
        from = "Column::Leads",
        to = "super::teams::Column::Name",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Teams2,
    #[sea_orm(
        belongs_to = "super::teams::Entity",
        from = "Column::TeamName",
        to = "super::teams::Column::Name",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Teams1,
}

impl ActiveModelBehavior for ActiveModel {}
